# market-lab/render.yaml
# Este blueprint define todos os serviços que serão implantados no Render.
services:
  - type: web
    name: market-lab-eureka
    env: docker
    rootDir: eureka-server
    plan: free
    autoDeploy: true
    ports: [{ port: 8761, name: eureka-port }]
    
  - type: web
    name: market-lab-gateway
    env: docker
    rootDir: api-gateway
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_CLIENT_SERVICE_URL
        value: http://market-lab-eureka:8761/eureka
    ports: [{ port: 8080, name: http }]
    
  - type: web
    name: market-lab-product
    env: docker
    rootDir: product-service
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_CLIENT_SERVICE_URL
        value: http://market-lab-eureka:8761/eureka
      - key: CACHE_TYPE
        value: simple
        
  - type: web
    name: market-lab-order
    env: docker
    rootDir: order-service
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_CLIENT_SERVICE_URL
        value: http://market-lab-eureka:8761/eureka
