# market-lab/render.yaml
services:
  - type: web
    name: market-lab-eureka
    env: docker
    rootDir: eureka-server
    plan: free
    autoDeploy: true

  - type: web
    name: market-lab-gateway
    env: docker
    rootDir: api-gateway
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_SERVER_URL
        value: https://market-lab-eureka.onrender.com/eureka # 🔑 Atualizar depois do deploy do Eureka

  - type: web
    name: market-lab-product
    env: docker
    rootDir: product-service
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_SERVER_URL
        value: https://market-lab-eureka.onrender.com/eureka # 🔑 Atualizar depois do deploy do Eureka
      - key: CACHE_TYPE
        value: simple

  - type: web
    name: market-lab-order
    env: docker
    rootDir: order-service
    plan: free
    autoDeploy: true
    envVars:
      - key: EUREKA_SERVER_URL
        value: https://market-lab-eureka.onrender.com/eureka # 🔑 Atualizar depois do deploy do Eureka
