# market-lab/render.yaml
# Este blueprint define todos os serviços que serão implantados no Render.
services:
  # Servidor Eureka (Service Discovery)
  - type: web
    name: market-lab-eureka
    env: docker
    rootDir: eureka-server
    plan: free
    autoDeploy: true

  # API Gateway
  - type: web
    name: market-lab-gateway
    env: docker
    rootDir: api-gateway
    plan: free
    autoDeploy: true

  # Serviço de Catálogo de Produtos
  - type: web
    name: market-lab-product
    env: docker
    rootDir: product-service
    plan: free
    autoDeploy: true

  # Serviço de Pedidos
  - type: web
    name: market-lab-order
    env: docker
    rootDir: order-service
    plan: free
    autoDeploy: true
