# Configuração do API Gateway
server:
  port: ${PORT:0} # Porta dinâmica para compatibilidade com Render

spring:
  application:
    name: api-gateway # Nome do serviço no Eureka

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # garante que os nomes dos serviços sejam minúsculos
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
