# Configuração do Serviço de Pedidos
server:
  port: ${PORT:0} # Usa a porta definida pelo Render ou gera uma aleatória localmente

spring:
  application:
    name: order-service # Nome do serviço para registro no Eureka

eureka:
  instance:
    # Usa o IP ao invés do hostname (mais estável em Docker/Render)
    prefer-ip-address: true
    # ID único para cada instância (evita conflitos quando várias instâncias sobem)
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    serviceUrl:
      # Obtém a URL do Eureka da variável de ambiente definida no Render.yaml
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
