# Configuração do Serviço de Pedidos
server:
  port: 0

spring:
  application:
    name: order-service # Nome do serviço para registro no Eureka

eureka:
  client:
    serviceUrl:
      # Obtém a URL do Eureka da variável de ambiente definida no Render.yaml
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
