server:
  port: ${PORT:8081}

spring:
  application:
    name: order-service

eureka:
  instance:
    # A linha abaixo foi removida.
    # prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:https://market-lab-eureka.onrender.com/eureka}
