server:
  port: 8081
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:products;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  cache:
    type: ${CACHE_TYPE:redis}  # se não houver REDIS_URL cai para erro → ajuste via env; ou use caffeine local: set CACHE_TYPE=simple
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
# Redis opcional
redis:
  url: ${REDIS_URL:}
