server:
  port: ${PORT:0} # Usa a porta do Render, ou aleatória localmente

spring:
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:https://market-lab-eureka.onrender.com/eureka}
