# Configuração do Serviço de Produtos
server:
  port: 0 # Porta aleatória

spring:
  application:
    name: product-service # Nome usado no Eureka e no API Gateway

eureka:
  instance:
    prefer-ip-address: true # Garante que registre com IP em vez de hostname
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
      
