server:
  port: ${PORT:8081} # Agora usa a porta do Render ou 8081 localmente

spring:
  application:
    name: PRODUCT-SERVICE

eureka:
  # Removido: prefer-ip-address: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:https://market-lab-eureka.onrender.com/eureka}
