server:
  port: 8761

eureka:
  instance:
    # Use a URL pública do seu servidor Eureka
    hostname: market-lab-eureka.onrender.com 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # A URL de registro é a sua própria URL pública
      defaultZone: https://market-lab-eureka.onrender.com/eureka
